### ISSUE TITLE
Downloading weather data fails for some stations / picking the most accurate station ID list

### ISSUE THREAD

**Issue by BenaniZ** [RWTH-EBC/AixWeather#24]
**Describe the bug**
When trying to create a csv-file with the AixWeather-WebApp, for some stations the created file is empty, although data is available in https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/air_temperature/historical/. 

**To Reproduce**
Can be reproduced for Ahaus (ID: 7374) or Berlin-Tempelhof (ID: 433), which have broad data sets and are still in service according to this ID-List: https://www.dwd.de/DE/leistungen/klimadatendeutschland/statliste/statlex_rich.txt;jsessionid=68E14BA255FE50BDC4AD9FF4F835895F.live31092?view=nasPublication&nn=16102

1. In the AixWeather-WebApp type in the ID 7374 or 433 
2. Select 2017-01-01 until 2017-12-31 and click on download
3. Check the downloaded csv-file. It should be empty.
4. Now check the dwd database for hourly values (TU) here: https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/air_temperature/historical/
5. Download the respective folder for station 7374 or 433
6. Check the downloaded folder. There should be a file named product_tu_stunde_[...]. This file should contain all the hourly values for the respective station until 2022.

**Expected behavior**
The csv-file should contain the weather data that is visible when doing a manual download from the dwd database.

**Additional context**
I have pursued three possible causes:
1. Data allocation only working for stations that were inaugurated after 2007 like Aachen-Orsbach (ID: 15000) or Waibstadt (ID: 13674). However, downloaded data for Eisenach, which was inaugurated in 2007 (ID: 7368), is empty.

2. Data allocation only working for stations with 5-digit ID-number (Aachen/Waibstadt). I tried out some other stations like Offenbach-Wetterpark (ID: 7341) or Helmstedt-Emmerstedt (ID: 13777) that confirm this thesis. However, i can't comprehend why.

3. Incomplete data-sets. The table from above "https://www.dwd.de/DE/leistungen/klimadatendeutschland/statliste/statlex_rich.txt;jsessionid=68E14BA255FE50BDC4AD9FF4F835895F.live31092?view=nasPublication&nn=16102" gives information on the extent of data which is available for each station. You can check the column KE (Kennung) and compare it with the table "Kennung-Übersicht" here: "https://www.dwd.de/DE/leistungen/klimadatendeutschland/stationsliste.html". However, Ahaus and Berlin-Tempelhof cover the same extent of data as Aachen-Orsbach and Waibstadt.

**Bug Fix Suggestion**
I did not find any possible solutions yet, but I recommend to attach the dwd station list from above instead of the current list. The current list only gives information on the availability of temperature and moisture data.

**Comment by MartinRaetz** [comment]
Hello @BenaniZ, and thank you for this well-documented issue!
This is a bug, indeed!

AixWeather does access the same files via HTTP as you did. 
So, it should load that data. There is also a distinction between historical and recent data at the DWD, so that might be currently in the year 2017 leading to this behavior. But this is not the problem.

Your second possible cause turned out to be the origin of the bug. Thank you for providing the info!

In the file:
aixweather/imports/DWD.py function "import_DWD_historical".

- [ ] DWD data contains the stations with leading zeros, the meta-data, and station lists without leading zeros. Apply leading zeros for pulling DWD data.

You will find the fix in the related branch to this issue. Unfortunately, it takes a few steps until these changes are merged through and deployed in the web app. So, I invite you to test it locally directly through AixWeather by running the example file with your specifications. I would be happy if you could confirm that all your issues are fixed.

**Comment by MartinRaetz** [comment]
I also added your station list overview to the web app and readme as I find it more informative. 
Your suggested list was already added in a prior fix which currently waits for its deployment.

- [ ] add https://www.dwd.de/DE/leistungen/klimadatendeutschland/stationsliste.html to readme and webapp

**Comment by BenaniZ** [comment]
Thank you for providing a fix for this issue! I can confirm that the issue is solved now.
