### ISSUE TITLE
Importing an epw file with different years for each month 

### ISSUE THREAD

**Issue by TobiasSpratte** [RWTH-EBC/AixWeather#43]
**Describe the bug**
Importing an epw file with different years for each month (TMY) and exporting it again lead to missing values. All months with a year lower than the year of the first of January are removed.

**To Reproduce**
1. Import an epw TMY file 
2. Export to epw
3. Compare input file and output file

**Expected behavior**
Same length and same values.

**Screenshots**
![image](https://github.com/RWTH-EBC/AixWeather/assets/135248974/6a58c22d-719c-4d75-821d-a51365bf3df5)
![image](https://github.com/RWTH-EBC/AixWeather/assets/135248974/0631f2da-56bb-427f-affd-03b745955977)
First image: Input
Second image: Output

**Bug Fix Suggestion**
Option1: Check, whether there are different years in the epw file. In case of different years, override the years with the same year.

**Comment by MartinRaetz** [comment]
@TobiasSpratte thank you for opening the issue. 

Can you assess whether the information about the year is important to keep when outputting?
.mos does not have any years, so here it doesnt matter
.epw is actually the input format, but still, does EnergyPlus care about the year? I guess not, otherwise it would not simulate those files correctly.


About the input file, what would be a good detection strategy for finding such TMY files?
1. lines with data fill one year
2. lines with data have no dublettes if the year is deleted
Will this be enough to detect such a file, and simultaniously avoid changing years for file where it is not desired?

**Comment by TobiasSpratte** [comment]
The year information is not important for the simulation in EnergyPlus as EnergyPlus only uses the information on month, day and hour.

I think your suggested detection strategy should work. 

The year is not important for EnergyPlus. But maybe an user wants to keep the information about the year in the exported epw file. Do you think that we can keep the information with the following steps?

1. Save the year information
2. Override the years with one year to fill the dataframe correctly
3. Override the year with the initial year information. 
4. Export to epw.

**Comment by MartinRaetz** [comment]
@TobiasSpratte I have implemented a fix in the corresponding branch.

**Comment by MartinRaetz** [comment]
@TobiasSpratte please implement a test case with such an .epw TMY file. 

To safe work, you may merge this branch and the branch of #32 before creating the new test-result files.

**Comment by MartinRaetz** [comment]
I have done the merging, please continue to work in #32.

**Comment by MartinRaetz** [comment]
This will be closed with closing #32.
